config/routes.rb
Rails.application.routes.draw do
  get 'buyer/page'
  resources :accounts
  resources :cars
  resources :profiles
  devise_for :users
  root 'home#page'

  post '/payment', to: "buyer#payment"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def page
    @cars = Car.all
    @avatar = Avatar.first
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/page.html.erb
<div class="d-flex justify-content-center">
    <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
</div>

<div class="row mt-5">
    <% @cars.each do |car| %>
        <div class="col-md-4 mt-5">
            <div class="card">
            <%# check if the image is there, if not set default pic %>
            <% if car.pictures.first.present? %>
                <%= image_tag car.pictures.first, class: "card-img-top" %>
            <%elsif car.pictures.second.present? %>
                <%= image_tag car.pictures.second, class: "card-img-top" %>
            <%else%>
                <%= image_tag "default.PNG", class: "card-img-top" %>
            <%end%>

                <div class="card-body">
                    <h5 class="card-title"><%=car.make%> <%=car.model%></h5>
                    <p class="card-text">$<%=car.price%>0</p>
                    <%= link_to "Have a closer look", car_path(car.id), class: "btn btn-primary"%>
                </div>
            </div>
        </div>
        
    <%end%>
</div>

app/views/home/pages_backup.html.erb
<div class="d-flex justify-content-center">
    <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
</div>
<h1>Home#page</h1>
<div class="card-deck">
        <% @cars.each do |car| %>
        <%# this div card is copied straight from bootstrap %>
        <div class="col-sm-4">
            <div class="card">
                <%= image_tag car.pictures.first %>
                <div class = "card-body">
                    <p class="card-text">
                        <%=car.model%> <%=car.make%>
                    </p>
                    <p>
                        <a href= "car_path" class="btn btn-primary">Show: $<%= car.price%></a>
                    </p>
                </div>
            </div>
        </div>
    <%end%>
</div>
<div class="card" style="width: 18rem;">
  <img class="card-img-top" src="..." alt="Card image cap">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href= car_path class="btn btn-primary">Go somewhere</a>
  </div>
</div>