config/routes.rb
Rails.application.routes.draw do
  get 'buyer/page'
  resources :accounts
  resources :cars
  resources :profiles
  devise_for :users
  root 'home#page'

  post '/payment', to: "buyer#payment"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ApplicationRecord
    belongs_to :seller
    #associate to the active storage images
    has_many_attached :pictures
    belongs_to :buyer
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    if current_user
        if current_user.profile
          @car = Car.new
        else
          redirect_to new_profile_path
        end
    else 
      redirect_to new_user_session_path
    end
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    @seller = Seller.new #need to create a seller so we can link them
    @seller.profile_id = current_user.profile.id
    @seller.save
    # link seller_id to car model
    @car.seller_id = current_user.profile.seller.id 

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    if @car.pictures
      @car.pictures.purge
    end
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:make, :model, :year, :km, :price, :color, :rego, :description, :fuel_type, :transmission_type, :location, pictures: [])
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= simple_form_for(@car) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :make %>
    <%= f.input :model %>
    <%= f.input :year %>
    <%= f.input :km %>
    <%= f.input :price %>
    <%= f.input :color, collection: ["red", "blue", "yellow", "black", "white", "grey", "silver", "other"] %>
    <%="Registration Expiry Date"%>
    <%= f.date_field :rego, label: "Registration expiry date" %>
    <br>
    <br>
    <%= f.input :description %>
    <%= f.input :fuel_type, collection: ["Petrol", "Diesel", "Hybrid"] %>
    <%= f.input :transmission_type, collection: ["Automatic", "Manual"] %>
    <%= f.input :location %>
    <%= f.file_field :pictures, multiple: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Picture</th>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th>Km</th>
      <th>Price</th>
      <th>Color</th>
      <th>Rego</th>
      <th>Description</th>
      <th>Fuel type</th>
      <th>Transmission type</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.picture %></td>
        <td><%= car.make %></td>
        <td><%= car.model %></td>
        <td><%= car.year %></td>
        <td><%= car.km %></td>
        <td><%= car.price %></td>
        <td><%= car.color %></td>
        <td><%= car.rego %></td>
        <td><%= car.description %></td>
        <td><%= car.fuel_type %></td>
        <td><%= car.transmission_type %></td>
        <td><%= car.location %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>
<div class = "row">
  <div class = "col-md-8">
    <div class = "row">
      <%= @car.pictures.each do |picture|%>
        <div class="col-md-6">
          <%= image_tag picture, class: "d-block w-100"%>
        </div>
      <%end%>
    </div>
  </div>
  <div class = "col-md-4">
    <p>
      <strong>Make:</strong>
      <%= @car.make %>
    </p>

    <p>
      <strong>Model:</strong>
      <%= @car.model %>
    </p>

    <p>
      <strong>Year:</strong>
      <%= @car.year %>
    </p>

    <p>
      <strong>Km:</strong>
      <%= @car.km %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @car.price %>
    </p>

    <p>
      <strong>Color:</strong>
      <%= @car.color %>
    </p>

    <p>
      <strong>Rego:</strong>
      <%= @car.rego %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @car.description %>
    </p>

    <p>
      <strong>Fuel type:</strong>
      <%= @car.fuel_type %>
    </p>

    <p>
      <strong>Transmission type:</strong>
      <%= @car.transmission_type %>
    </p>

    <p>
      <strong>Location:</strong>
      <%= @car.location %>
    </p>
  </div>
</div>

<%# if listed car is by the seller who has logged in, show edit button, else show buy button %>
<% if (current_user && current_user.profile && (current_user.profile.id == @car.seller.profile_id)) %>
  <%= link_to 'Edit', edit_car_path(@car) %> |
<% else %>
  <% if current_user && current_user.profile &&current_user.profile.buyer%>
    <%= link_to 'Buy', buyer_page_path(car_id: @car.id, seller_id: @car.seller_id), class: "btn btn-primary" %>
    <%end%>
<%end%>
<%= link_to 'Back', cars_path %> 